run:
  timeout: 5m
  modules-download-mode: vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gosec
    - misspell
    - nolintlint

linters-settings:
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
  gosec:
    excludes:
      - G104

issues:
  exclude-dirs:
    - vendor
    - testdata
  exclude-files:
    - ".*_test\\.go$"
    - ".*/mock/.*\\.go$"
  max-issues-per-linter: 50
  max-same-issues: 5
