version: "2"
run:
  modules-download-mode: vendor
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - nolintlint
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
    gosec:
      excludes:
        - G104
    govet:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test\.go$
      - .*/mock/.*\.go$
      - vendor
      - testdata
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
