#!/command/with-contenv bash

log_info() {
    printf 'time="%s" level=info msg="%s" type=filesystem\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$1"
}

# Only run if filesystem collection is enabled
if [ -z "${COLLECTOR_FILESYSTEM_CRON_SCHEDULE}" ] && [ "${COLLECTOR_FILESYSTEM_RUN_STARTUP}" != "true" ]; then
    log_info "Filesystem collector not enabled"
    s6-svc -D /run/service/collector-filesystem-once
    exit 0
fi

# ensure not run before
if [ -f /tmp/filesystem-collector-init-performed ]; then
    log_info "Filesystem collector init already performed"
    s6-svc -D /run/service/collector-filesystem-once
    exit 0
fi

log_info "waiting for scrutiny service to start"
s6-svwait -u /run/service/scrutiny

# wait until scrutiny is "Ready"
until $(curl --output /dev/null --silent --head --fail http://localhost:8080/api/health); do log_info "scrutiny api not ready" && sleep 5; done

log_info "starting filesystem collector (run-once mode)"
COLLECTOR_CRON_SCHEDULE= /opt/scrutiny/bin/scrutiny-collector-filesystem run

touch /tmp/filesystem-collector-init-performed
s6-svc -D /run/service/collector-filesystem-once

exit 0
