#!/command/with-contenv bash

# Only run if filesystem collection is enabled
if [ -z "${COLLECTOR_FILESYSTEM_CRON_SCHEDULE}" ] && [ "${COLLECTOR_FILESYSTEM_RUN_STARTUP}" != "true" ]; then
    echo 'INFO: Filesystem collector not enabled'
    s6-svc -D /run/service/collector-filesystem-once
    exit 0
fi

# ensure not run before
if [ -f /tmp/filesystem-collector-init-performed ]; then
    echo 'INFO: Filesystem collector init already performed'
    s6-svc -D /run/service/collector-filesystem-once
    exit 0
fi

echo "waiting for scrutiny service to start"
s6-svwait -u /run/service/scrutiny

# wait until scrutiny is "Ready"
until $(curl --output /dev/null --silent --head --fail http://localhost:8080/api/health); do echo "scrutiny api not ready" && sleep 5; done

echo "starting filesystem collector (run-once mode)"
COLLECTOR_CRON_SCHEDULE= /opt/scrutiny/bin/scrutiny-collector-filesystem run

touch /tmp/filesystem-collector-init-performed
s6-svc -D /run/service/collector-filesystem-once

exit 0
