#!/command/with-contenv bash

log_info() {
    printf 'time="%s" level=info msg="%s" type=mdadm\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$1"
}

# Only run if MDADM collection is enabled
if [ -z "${COLLECTOR_MDADM_CRON_SCHEDULE}" ] && [ "${COLLECTOR_MDADM_RUN_STARTUP}" != "true" ]; then
    log_info "MDADM collector not enabled"
    s6-svc -D /run/service/collector-mdadm-once
    exit 0
fi

# ensure not run before
if [ -f /tmp/mdadm-collector-init-performed ]; then
    log_info "MDADM collector init already performed"
    s6-svc -D /run/service/collector-mdadm-once
    exit 0
fi

log_info "waiting for scrutiny service to start"
s6-svwait -u /run/service/scrutiny

# wait until scrutiny is "Ready"
until $(curl --output /dev/null --silent --head --fail http://localhost:8080/api/health); do log_info "scrutiny api not ready" && sleep 5; done

log_info "starting MDADM collector (run-once mode)"
COLLECTOR_CRON_SCHEDULE= COLLECTOR_MDADM_RUN_STARTUP= /opt/scrutiny/bin/scrutiny-collector-mdadm run

touch /tmp/mdadm-collector-init-performed
s6-svc -D /run/service/collector-mdadm-once

exit 0
