#!/command/with-contenv bash

# Only run if MDADM collection is enabled
if [ -z "${COLLECTOR_MDADM_CRON_SCHEDULE}" ] && [ "${COLLECTOR_MDADM_RUN_STARTUP}" != "true" ]; then
    echo 'INFO: MDADM collector not enabled'
    s6-svc -D /run/service/collector-mdadm-once
    exit 0
fi

# ensure not run before
if [ -f /tmp/mdadm-collector-init-performed ]; then
    echo 'INFO: MDADM collector init already performed'
    s6-svc -D /run/service/collector-mdadm-once
    exit 0
fi

echo "waiting for scrutiny service to start"
s6-svwait -u /run/service/scrutiny

# wait until scrutiny is "Ready"
until $(curl --output /dev/null --silent --head --fail http://localhost:8080/api/health); do echo "scrutiny api not ready" && sleep 5; done

echo "starting MDADM collector (run-once mode)"
COLLECTOR_CRON_SCHEDULE= COLLECTOR_MDADM_RUN_STARTUP= /opt/scrutiny/bin/scrutiny-collector-mdadm run

touch /tmp/mdadm-collector-init-performed
s6-svc -D /run/service/collector-mdadm-once

exit 0
