#!/command/with-contenv bash

log_info() {
    printf 'time="%s" level=info msg="%s" type=influxdb\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$1"
}

/usr/local/bin/scrutiny-influxdb-upgrade-preflight

mkdir -p /opt/scrutiny/influxdb/

if [ -f "/opt/scrutiny/influxdb/config.yaml" ]; then
    log_info "influxdb config file already exists. skipping."
else
cat << 'EOF' > /opt/scrutiny/influxdb/config.yaml
bolt-path: /opt/scrutiny/influxdb/influxd.bolt
engine-path: /opt/scrutiny/influxdb/engine
http-bind-address: ":8086"
reporting-disabled: true
storage-cache-max-memory-size: 256000000
storage-cache-snapshot-memory-size: 25000000
EOF
fi

log_info "starting influxdb"
exec influxd run
