#!/command/with-contenv bash

log_info() {
    printf 'time="%s" level=info msg="%s" type=zfs\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$1"
}

# Only run if ZFS collection is enabled
if [ -z "${COLLECTOR_ZFS_CRON_SCHEDULE}" ] && [ "${COLLECTOR_ZFS_RUN_STARTUP}" != "true" ]; then
    log_info "ZFS collector not enabled"
    s6-svc -D /run/service/collector-zfs-once
    exit 0
fi

# ensure not run before
if [ -f /tmp/zfs-collector-init-performed ]; then
    log_info "ZFS collector init already performed"
    s6-svc -D /run/service/collector-zfs-once
    exit 0
fi

log_info "waiting for scrutiny service to start"
s6-svwait -u /run/service/scrutiny

# wait until scrutiny is "Ready"
until $(curl --output /dev/null --silent --head --fail http://localhost:8080/api/health); do log_info "scrutiny api not ready" && sleep 5; done

log_info "starting ZFS collector (run-once mode)"
COLLECTOR_CRON_SCHEDULE= /opt/scrutiny/bin/scrutiny-collector-zfs run

touch /tmp/zfs-collector-init-performed
s6-svc -D /run/service/collector-zfs-once

exit 0
